### ISSUE TITLE
Integration test needs an ID generator, to deal with the random ID currently generated by ZK 

### ISSUE THREAD

**Issue by chengengliu** [omjadas/swen90013-bp#59]
@chengengliu there is now an issue with the test that will have to be fixed

_Originally posted by @omjadas in https://github.com/omjadas/swen90013-bp/pull/57#issuecomment-640221108_

**Comment by chengengliu** [comment]
To be more specific, in the current integration test, we are using Selenium, which imitate the behaviour of a user, for example click the button and upload file to see if the result/ eye icon is shown on the page. But one thing makes it hard to click the button is that, ZK intentionally use random id of components to avoid CSRF attack for security purpose. This random ID makes it difficult to find which button for Selenium to click. I was thinking adding a tag for each component, but the 'submit' button doesn't seem configurable(not too sure about it, will look into it further).

**Comment by mayankgituni** [comment]
Interesting, I will look into it and maybe we can dicuss this.

**Comment by chengengliu** [comment]
[BP-72](https://swen90013-bp.atlassian.net/browse/BP-72)
