### ISSUE TITLE
Mutiple file upload with same name will not work.

### ISSUE THREAD

**Issue by mayankgituni** [omjadas/swen90013-bp#63]
As suggested by @jay1805 and @Janite - Even though the user may not upload the same file name with the same extension the case where users upload the same file name with a different extension may be a possibility. 

Possible solution: We can check the input file name in the stored volume and if the file name is already taken then we can append a number i.e. fileName_[i] for each repeating file imports. Furthermore, we can let the user change the name of the file after importing so they don't have to deal with the same file name at run time.

**Comment by mayankgituni** [comment]
@chengengliu What do you think about this issue? It seems we might need to add some logic in the file handler service.

**Comment by chengengliu** [comment]
> @chengengliu What do you think about this issue? It seems we might need to add some logic in the file handler service.

Yes you are right. It’s doable. I think we can have some data structures(for example a List) storing the uploaded file(name ) and before the Media file is uploaded, call the Impala service, check if the name is added or not.

**Comment by mayankgituni** [comment]
Do you think we would need the list of the stored files in the volume or the loaded tables in the impala? Or both?

**Comment by omjadas** [comment]
BP-71
